version: '3'
services:
  app:
    build: .
    image: currency-converter:1.0
    ports:
      - "5000:8080"
    env_file:
      - .env
    volumes:
      - ./src/:/app
      - /app/bin
      - /app/obj
