apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ../docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: app
  name: app
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      nodePort: 30000
      targetPort: 8080
  selector:
    io.kompose.service: app
